language: cpp
compiler:
  - clang
#  - gcc
env:
  global:
    - MAKE_CMD="make -j2"
  
os:
- linux
dist: trusty
addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - lcov
          - libboost-test-dev
          - cmake-data
          - cmake
 #         - g++-7
          - clang-5.0 


script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir release_build
  - cd release_build
  - cmake ..
  - make
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir coverage_build
  - cd coverage_build
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  - make hello_coverage
after_success:
  - cd ${TRAVIS_BUILD_DIR}/coverage_build
  - lcov --list coverage.info #Show stats in log 
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"


jobs: 
  include:
    -stage: deploy
    if: branch = master
